In [2]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
a = [1,2,3.7,"addy"]

In [7]:
np.array(a)

array(['1', '2', '3.7', 'addy'], dtype='<U32')

In [8]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr = np.zeros((4,8)) #rows,columns
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
arr = np.ones((3,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
arr = np.linspace(1,10,8)
arr

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [29]:
np.random.rand(10) #normalisation

array([0.97238809, 0.76825617, 0.91388055, 0.14468747, 0.95176155,
       0.75152461, 0.09759063, 0.67194361, 0.86654817, 0.47595764])

In [30]:
np.random.randn(10) #standardisation

array([-0.05757802, -0.48100393,  0.33859335,  0.01935343, -0.83995328,
        0.43523193, -0.65860625, -0.33765953,  1.42990522,  1.05370616])

In [31]:
np.random.randint(10,20,10)

array([12, 16, 17, 17, 17, 12, 19, 17, 13, 19], dtype=int32)

In [36]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr.shape

(3, 3)