In [2]:
import numpy as np

In [7]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [9]:
arr[1:5]

array([12, 13, 14, 15])

In [10]:
arr = np.arange(1,31).reshape(6,5)

In [11]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [15]:
arr[5]

array([26, 27, 28, 29, 30])

In [16]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])