In [1]:
import numpy as np 

In [8]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [9]:
a1 + a2 

array([ 7,  9, 11, 13, 15])

In [10]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [11]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [12]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [13]:
a1// a2

array([0, 0, 0, 0, 0])

In [14]:
a1 % a2

array([1, 2, 3, 4, 5])

In [15]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [17]:
l = [10,20,30,40]
arr = np.array(l)
arr

array([10, 20, 30, 40])

In [18]:
arr + 10

array([20, 30, 40, 50])

In [19]:
arr * 10

array([100, 200, 300, 400])

In [20]:
arr / 10

array([1., 2., 3., 4.])

In [23]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [25]:
# or np.dot(A,B)
A @ B

array([[19, 22],
       [43, 50]])

In [26]:
A

array([[1, 2],
       [3, 4]])

In [27]:
A.transpose()

array([[1, 3],
       [2, 4]])

In [28]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [30]:
np.vstack((a1,a2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [31]:
np.hstack((a1,a2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
np.column_stack((a1,a2))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [33]:
c = np.arange(1,21).reshape(5,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [34]:
np.split(c,5)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]]),
 array([[17, 18, 19, 20]])]

In [37]:
np.vsplit(c,5)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]]),
 array([[17, 18, 19, 20]])]

In [38]:
np.hsplit(c,4)

[array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]]),
 array([[ 4],
        [ 8],
        [12],
        [16],
        [20]])]

In [39]:
np.hsplit(c,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20]])]