In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
a = [1,2,3.7,"addy"]

In [4]:
np.array(a)

array(['1', '2', '3.7', 'addy'], dtype='<U32')

In [5]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr = np.zeros((4,8)) #rows,columns
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
arr = np.ones((3,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
arr = np.linspace(1,10,8)
arr

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [11]:
np.random.rand(10) #normalisation

array([0.39148149, 0.841909  , 0.71100061, 0.55893667, 0.92554111,
       0.50474529, 0.27012395, 0.38889413, 0.98669989, 0.59995472])

In [12]:
np.random.randn(10) #standardisation

array([-0.48910286, -0.72793138,  0.59389558, -0.28004374,  0.52426377,
       -0.59050959, -1.67590426,  0.29155409, -0.71626422, -0.84881756])

In [13]:
np.random.randint(10,20,10)

array([17, 10, 11, 17, 18, 14, 13, 16, 15, 18], dtype=int32)

In [14]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr.shape

(3, 3)

In [16]:
 arr.min()

np.int64(1)

In [17]:
arr.max()

np.int64(9)

In [18]:
arr.sum()

np.int64(45)

In [20]:
np.sum(arr,axis=0)  #for column wise sum

array([12, 15, 18])

In [23]:
np.sum(arr,axis=1)  #for row wise sum 

array([ 6, 15, 24])

In [24]:
arr.mean()

np.float64(5.0)

In [25]:
arr.std()

np.float64(2.581988897471611)

In [26]:
arr.argmax()

np.int64(8)

In [27]:
arr.argmin()

np.int64(0)

In [29]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [32]:
arr = arr.reshape(6,5)

In [33]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])