In [1]:
import numpy as np

**Valid Sudoku**

In [2]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [3]:
s.sum() #column axis is zero and rows axis is one 

np.int64(405)

In [4]:
b = np.sum(s, axis = 1)
b == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [5]:
for i in b:
    if i != 45:
        print("Sudoku is not valid")
        break 
else:
    print("for rows it is valid")

for rows it is valid


In [6]:
b = np.sum(s, axis = 0)
for i in b:
    if i != 45:
        print("Sudoku is not valid")
        break 
else:
    print("for Columns it is valid")


for Columns it is valid


In [7]:
block1 = s[:3,:3]
block1

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [8]:
block2 = s[3:6,3:6]
block2

array([[7, 6, 1],
       [8, 5, 3],
       [9, 2, 4]])

In [21]:
#but there is a better way 
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [36]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [37]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [38]:
#Find the average age of students.
age = data[:5,0]
age.mean()

np.float64(18.4)

In [39]:
#Extract Math marks of all students.
Maths = data[:,1]
Maths

array([85, 92, 76, 65, 90])

In [40]:
#Find the highest Science mark.
science = data[:,2]
science.max()
#np.max(data[;,2])

np.int64(95)

In [44]:
#Get details of the student who scored more than 90 in Math.
data[Maths > 90]


array([[19, 92, 88]])

In [45]:
#Increase Math marks of all students by 5.
Maths + 5

array([90, 97, 81, 70, 95])

In [51]:
#Find how many students are younger than 19.
len(data[age < 19])

3

In [55]:
#Calculate the average marks in each subject (column-wise mean).
a = science.mean()
b = Maths.mean()
print(a,b)

83.2 81.6


In [59]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [61]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2] < 75] = 0
data


array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])